GET http://localhost:3000/user/KHVanitas/favorites HTTP/1.1

###

DELETE http://localhost:3000/user/exist/account HTTP/1.1
Content-Type: application/json

{
    "password": "right"
}

###

POST http://localhost:3000/user/register HTTP/1.1
Content-Type: application/json

{
    "username": "exist",
    "email": "exist@test.test",
    "password": "right"
}

###

GET http://localhost:3000/location HTTP/1.1
Content-Type: application/json

{
    "cityName": "berlin",
    "countryName": "",
    "stateCode": "",
    "zipCode": "",
    "latitude": "",
    "longitude": ""
}

###

GET http://localhost:3000/location/presentFuture HTTP/1.1
Content-Type: application/json

{
    "cityName": "berlin",
    "countryName": "",
    "stateCode": "",
    "zipCode": "",
    "latitude": "",
    "longitude": ""
}

###

GET http://localhost:3000/location/past HTTP/1.1
Content-Type: application/json

{
    "cityName": "berlin",
    "countryName": "",
    "stateCode": "",
    "zipCode": "",
    "latitude": "",
    "longitude": ""
}