module.exports = {
  oneCall: {
    currentAndForecastWeatherData: {
      lat: 33.44,
      lon: -94.04,
      timezone: 'America/Chicago',
      timezone_offset: -21600,
      current: {
        dt: 1618317040,
        sunrise: 1618282134,
        sunset: 1618333901,
        temp: 284.07,
        feels_like: 282.84,
        pressure: 1019,
        humidity: 62,
        dew_point: 277.08,
        uvi: 0.89,
        clouds: 0,
        visibility: 10000,
        wind_speed: 6,
        wind_deg: 300,
        wind_gust: 7.33,
        weather: [
          {
            id: 500,
            main: 'Rain',
            description: 'light rain',
            icon: '10d',
          },
        ],
        rain: {
          '1h': 0.21,
        },
      },
      minutely: [
        {
          dt: 1618317060,
          precipitation: 0.205,
        },
      ],
      hourly: [
        {
          dt: 1618315200,
          temp: 282.58,
          feels_like: 280.4,
          pressure: 1019,
          humidity: 68,
          dew_point: 276.98,
          uvi: 1.4,
          clouds: 19,
          visibility: 306,
          wind_speed: 4.12,
          wind_deg: 296,
          wind_gust: 7.33,
          weather: [
            {
              id: 801,
              main: 'Clouds',
              description: 'few clouds',
              icon: '02d',
            },
          ],
          pop: 0,
        },
      ],
      daily: [
        {
          dt: 1618308000,
          sunrise: 1618282134,
          sunset: 1618333901,
          moonrise: 1618284960,
          moonset: 1618339740,
          moon_phase: 0.04,
          temp: {
            day: 279.79,
            min: 275.09,
            max: 284.07,
            night: 275.09,
            eve: 279.21,
            morn: 278.49,
          },
          feels_like: {
            day: 277.59,
            night: 276.27,
            eve: 276.49,
            morn: 276.27,
          },
          pressure: 1020,
          humidity: 81,
          dew_point: 276.77,
          wind_speed: 3.06,
          wind_deg: 294,
          wind_gust: 7.33,
          weather: [
            {
              id: 500,
              main: 'Rain',
              description: 'light rain',
              icon: '10d',
            },
          ],
          clouds: 56,
          pop: 0.2,
          rain: 0.62,
          uvi: 1.93,
        },
      ],
      alerts: [
        {
          sender_name: 'NWS Tulsa',
          event: 'Heat Advisory',
          start: 1597341600,
          end: 1597366800,
          description:
            'HEAT ADVISORY REMAINS IN EFFECT FROM 1 PM THIS AFTERNOON TO\n8 PM CDT THIS EVENING\n* WHATHeat index values of 105 to 109 degrees expected.\n* WHERECreek, Okfuskee, Okmulgee, McIntosh, Pittsburg,\nLatimer, Pushmataha, and Choctaw Counties.\n* WHENFrom 1 PM to 8 PM CDT Thursday.\n* IMPACTSThe combination of hot temperatures and high\nhumidity will combine to create a dangerous situation in which\nheat illnesses are possible.',
          tags: ['Extreme temperature value'],
        },
      ],
    },
  },
  geocoding: {
    coordinatesByLocationName: [
      {
        name: 'London',
        local_names: {
          af: 'Londen',
          ar: 'لندن',
          ascii: 'London',
          az: 'London',
          bg: 'Лондон',
          ca: 'Londres',
          da: 'London',
          de: 'London',
          el: 'Λονδίνο',
          en: 'London',
          eu: 'Londres',
          fa: 'لندن',
          feature_name: 'London',
          fi: 'Lontoo',
          fr: 'Londres',
          gl: 'Londres',
          he: 'לונדון',
          hi: 'लंदन',
          hr: 'London',
          hu: 'London',
          id: 'London',
          it: 'Londra',
          ja: 'ロンドン',
          la: 'Londinium',
          lt: 'Londonas',
          mk: 'Лондон',
          nl: 'Londen',
          no: 'London',
          pl: 'Londyn',
          pt: 'Londres',
          ro: 'Londra',
          ru: 'Лондон',
          sk: 'Londýn',
          sl: 'London',
          sr: 'Лондон',
          th: 'ลอนดอน',
          tr: 'Londra',
          vi: 'Luân Đôn',
          zu: 'ILondon',
        },
        lat: 51.5085,
        lon: -0.1257,
        country: 'GB',
      },
      {
        name: 'London',
        local_names: {
          ar: 'لندن',
          ascii: 'London',
          bg: 'Лондон',
          de: 'London',
          en: 'London',
          fa: 'لندن، انتاریو',
          feature_name: 'London',
          fi: 'London',
          fr: 'London',
          he: 'לונדון',
          ja: 'ロンドン',
          lt: 'Londonas',
          nl: 'London',
          pl: 'London',
          pt: 'London',
          ru: 'Лондон',
          sr: 'Лондон',
        },
        lat: 42.9834,
        lon: -81.233,
        country: 'CA',
      },
      {
        name: 'London',
        local_names: {
          ar: 'لندن',
          ascii: 'London',
          en: 'London',
          fa: 'لندن، اوهایو',
          feature_name: 'London',
          sr: 'Ландон',
        },
        lat: 39.8865,
        lon: -83.4483,
        country: 'US',
        state: 'OH',
      },
      {
        name: 'London',
        local_names: {
          ar: 'لندن',
          ascii: 'London',
          en: 'London',
          fa: 'لندن، کنتاکی',
          feature_name: 'London',
          sr: 'Ландон',
        },
        lat: 37.129,
        lon: -84.0833,
        country: 'US',
        state: 'KY',
      },
      {
        name: 'London',
        local_names: {
          ascii: 'London',
          ca: 'Londres',
          en: 'London',
          feature_name: 'London',
        },
        lat: 36.4761,
        lon: -119.4432,
        country: 'US',
        state: 'CA',
      },
    ],
    coordinatesByZipOrPostCode: {
      zip: '90210',
      name: 'Beverly Hills',
      lat: 34.0901,
      lon: -118.4065,
      country: 'US',
      state: '',
    },
    reverseGeocoding: [
      {
        name: 'City of London',
        local_names: {
          ar: 'مدينة لندن',
          ascii: 'City of London',
          bg: 'Сити',
          ca: 'La City',
          de: 'London City',
          el: 'Σίτι του Λονδίνου',
          en: 'City of London',
          fa: 'سیتی لندن',
          feature_name: 'City of London',
          fi: 'Lontoon City',
          fr: 'Cité de Londres',
          gl: 'Cidade de Londres',
          he: 'הסיטי של לונדון',
          hi: 'सिटी ऑफ़ लंदन',
          id: 'Kota London',
          it: 'Londra',
          ja: 'シティ・オブ・ロンドン',
          la: 'Civitas Londinium',
          lt: 'Londono Sitis',
          pt: 'Cidade de Londres',
          ru: 'Сити',
          sr: 'Сити',
          th: 'นครลอนดอน',
          tr: 'Londra Şehri',
          vi: 'Thành phố Luân Đôn',
          zu: 'Idolobha weLondon',
        },
        lat: 51.5128,
        lon: -0.0918,
        country: 'GB',
        state: '',
      },
      {
        name: 'London',
        local_names: {
          af: 'Londen',
          ar: 'لندن',
          ascii: 'London',
          az: 'London',
          bg: 'Лондон',
          ca: 'Londres',
          da: 'London',
          de: 'London',
          el: 'Λονδίνο',
          en: 'London',
          eu: 'Londres',
          fa: 'لندن',
          feature_name: 'London',
          fi: 'Lontoo',
          fr: 'Londres',
          gl: 'Londres',
          he: 'לונדון',
          hi: 'लंदन',
          hr: 'London',
          hu: 'London',
          id: 'London',
          it: 'Londra',
          ja: 'ロンドン',
          la: 'Londinium',
          lt: 'Londonas',
          mk: 'Лондон',
          nl: 'Londen',
          no: 'London',
          pl: 'Londyn',
          pt: 'Londres',
          ro: 'Londra',
          ru: 'Лондон',
          sk: 'Londýn',
          sl: 'London',
          sr: 'Лондон',
          th: 'ลอนดอน',
          tr: 'Londra',
          vi: 'Luân Đôn',
          zu: 'ILondon',
        },
        lat: 51.5085,
        lon: -0.1257,
        country: 'GB',
      },
      {
        name: 'Islington',
        local_names: {
          ascii: 'Islington',
          az: 'İslinqton',
          fa: 'ایزلینتن',
          feature_name: 'Islington',
          fr: "District londonien d'Islington",
          he: 'איזלינגטון',
          ja: 'イズリントン',
          ru: 'Ислингтон',
        },
        lat: 51.5362,
        lon: -0.103,
        country: 'GB',
      },
      {
        name: 'Lewisham',
        local_names: {
          ascii: 'Lewisham',
          de: 'London Borough of Lewisham',
          en: 'Lewisham',
          feature_name: 'Lewisham',
          fi: 'Lewisham',
          fr: 'Lewisham',
          hu: 'Lewisham kerület',
          nl: 'Lewisham',
          no: 'Lewisham',
          ro: 'Lewisham',
        },
        lat: 51.4535,
        lon: -0.018,
        country: 'GB',
      },
      {
        name: 'Islington',
        local_names: {
          ascii: 'Islington',
          de: 'London Borough of Islington',
          en: 'Islington',
          feature_name: 'Islington',
          fr: 'Islington',
          nl: 'Islington',
          no: 'Islington',
          ro: 'Islington',
        },
        lat: 51.547,
        lon: -0.1094,
        country: 'GB',
      },
    ],
  },
};
