module.exports = {
  air_pressure: null,
  date: 0,
  fk_location_id: 0,
  fk_sky_state: null,
  fk_wind_direction: null,
  humidity: null,
  last_updated_unix: null,
  max_temperature: null,
  min_temperature: null,
  pk_weather_data_day_id: 1,
  precipitation_probability: null,
  sunrise: null,
  sunset: null,
  weather_report: null,
  wind_degree: null,
  wind_gust: null,
  wind_speed: null,
};
